var eye0url = "http://i.imgur.com/qR0I6iF.png";
var eye1url = "http://i.imgur.com/amIPKEs.png";
var eye2url = "http://i.imgur.com/ia6RZXL.png";
 

function crossHairsDraw() {
    stroke (255,255,0, 128);
    line (this.x,0,this.x,height); 
    line (0,this.y,width,this.y); 
}

function draw() {
 
    // Render the current image to the canvas.
    image(currentImage, 0, 0);
 
    // Initialize important variables. 
    var currentImageW = currentImage.width; 
    var currentImageH = currentImage.height;
    var crossHairs = {x: width/2, y: height/2, bright: -1, draw: crossHairsDraw};
    // var brightestPixelX = width/2; // provisional - fix me!
    // var brightestPixelY = height/2; // provisional - fix me!
 
    // Search for the brightest pixel in currentImage. 
    // Store its (x,y) location in brightestPixelX and brightestPixelY. 
    // Note: You might find the brightness() function to be helpful. 
    //
    // WRITE YOUR CODE HERE:
    // ...
    //var brightest = -1;

    for (var x=0; x<currentImageW; x++) {
    	for (var y=0; y<currentImageH; y++) {
    		var c = currentImage.get(x,y);
    		var b = brightness(c);
    		if (b > crossHairs.bright) {
    			crossHairs.x = x;
    			crossHairs.y = y;
    			crossHairs.bright = b;
    		}
    	}
    }
 
    crossHairs.draw();

    // Draw a crosshair to indicate the brightest pixel.

}
 
//================================================
// DO NOT MODIFY ANYTHING BELOW THIS LINE.
 
/*
// As an alternative to the above, you may fetch copies of these images from 
// imgur.com (full URLs appear above) and place them in the same directory 
// as sketch.js. (I've used the names generated by imgur.com. You can rename
// them as eye0.png, eye1.png, eye2.png if you also change the strings below.)
// After doing so, you can use the following for local deveopment: 
var eye0url = "qR0I6iF.png";
var eye1url = "amIPKEs.png";
var eye2url = "ia6RZXL.png";
*/
 
var eyeImage0;
var eyeImage1;
var eyeImage2;
var currentImageIndex;
 
function preload() {
    // Preload our images. 
    eyeImage0 = loadImage(eye0url);
    eyeImage1 = loadImage(eye1url);
    eyeImage2 = loadImage(eye2url);
    currentImageIndex = 0;
}
 
function setup() {
    // Create the canvas; make the pixels of the first image readable. 
    createCanvas(192, 143);
    currentImage = eyeImage0;
    currentImage.loadPixels();
}
 
function mousePressed(){
    // Select the next image; make its pixels readable.
    currentImageIndex = (currentImageIndex+1)%3; 
    if (currentImageIndex === 0){
      currentImage = eyeImage0;
    } else if (currentImageIndex === 1){
      currentImage = eyeImage1;
    } else if (currentImageIndex === 2){
      currentImage = eyeImage2;
    }
    currentImage.loadPixels();
}